In [1]:
import  numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
np.__version__

'1.21.4'

In [5]:
print(type(arr)) # tells us type of the given object

<class 'numpy.ndarray'>


In [6]:
arr2 = (('a','b','c','d','e',1,2,3,4,5))

print(arr2)

('a', 'b', 'c', 'd', 'e', 1, 2, 3, 4, 5)


In [7]:
# o-d array = array with one element
# 1-d array = array with a single row
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# 2-d array = array that as 1-d array as its elements
arr3 = ([[1,2,3],['a','b','c'],[4,5,6]])
arr3

[[1, 2, 3], ['a', 'b', 'c'], [4, 5, 6]]

In [9]:
# 3-d array = array that has 2-d aray as its elements
arr4 = ([[[1,2,3],[4,5,6]],[['a','b','c'],['d','e','f']],[[7,8,9],[10,11,12]]])
arr4 = np.array(arr4)
type(arr4)

numpy.ndarray

In [10]:
arr = np.array(arr) # to convert the intial list 'arr' to numpy array
arr3 = np.array(arr3)
arr4 = np.array(arr4)
# if we will not convert the list to ndarray, the
# numpy functions will not work on it
print("1-d array : \n",arr," Dimension : ",arr.ndim)
print("2-d array : \n",arr3," Dimension : ",arr3.ndim)
print("3-d array : \n",arr4," Dimension : ",arr4.ndim)
# ndarray.ndim function is used to find dimension of a numpy array

1-d array : 
 [ 1  2  3  4  5  6  7  8  9 10]  Dimension :  1
2-d array : 
 [['1' '2' '3']
 ['a' 'b' 'c']
 ['4' '5' '6']]  Dimension :  2
3-d array : 
 [[['1' '2' '3']
  ['4' '5' '6']]

 [['a' 'b' 'c']
  ['d' 'e' 'f']]

 [['7' '8' '9']
  ['10' '11' '12']]]  Dimension :  3


In [11]:
# We can define the number of dimensions by using the ndmin argument.
# Create an array with 5 dimensions and verify that it has 5 dimensions:
arr5 = np.array([1,2,3,4], ndmin = 5) # defining the dimension of the array
print(arr5)
print('Dimension : ',arr5.ndim)

[[[[[1 2 3 4]]]]]
Dimension :  5



In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

In [12]:
# esc + m = to change a cell to markdown cell

# Array Indexing

In [13]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
print(arr[3] + arr[5]) # arr[3] = 4, arr[5] = 6

10


In [15]:
# in 2-d arrays
print(arr3)

[['1' '2' '3']
 ['a' 'b' 'c']
 ['4' '5' '6']]


In [16]:
# 2nd element of row 1 , 3rd element of row 3, 1st element of row 2
print(arr3[0,1] , arr3[2,2],arr3[1,0])

2 6 a


In [17]:
# in 3-d arrays
print(arr4)

[[['1' '2' '3']
  ['4' '5' '6']]

 [['a' 'b' 'c']
  ['d' 'e' 'f']]

 [['7' '8' '9']
  ['10' '11' '12']]]


In [18]:
# 2nd element of the first array of the third array
print("arr\n[[3rd array -->],\n[1st array of 3rd array-->],\n[2nd element of the 1st array of 3rd array]]\n")
print(arr4[2,0,1])

arr
[[3rd array -->],
[1st array of 3rd array-->],
[2nd element of the 1st array of 3rd array]]

8


In [19]:
# negative indexing
print(arr3)

[['1' '2' '3']
 ['a' 'b' 'c']
 ['4' '5' '6']]


In [20]:
print(arr3[1,-1]) # 3rd element of the 2nd row

c


# Slicing arrays

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [21]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [22]:
# print [2,3,4,5] and then print[1,3,5,7,9]
print(arr[1:5])
print(arr[0:9:2]) # printig one elemrnt , leavin its consecutiove eleemnt, printing next element

[2 3 4 5]
[1 3 5 7 9]


In [23]:
print(arr[2:]) #from index 2 to last

[ 3  4  5  6  7  8  9 10]


In [24]:
print(arr[:7]) # from begining to element 6, 7 indexed not included

[1 2 3 4 5 6 7]


In [25]:
# negative slicing
print(arr[-3:-1]) # all the elements between 3rd and 1st element from the last

[8 9]


In [26]:
print(arr[4::2]) # every other elemrn from 4th index to last
print(arr[2:7:2]) # every other element from 2nd index to 7th index
print(arr[::2])# every other element from the beginning 

[5 7 9]
[3 5 7]
[1 3 5 7 9]


In [27]:
# Slicing in 2-d Arrays

In [28]:
print(arr3)

[['1' '2' '3']
 ['a' 'b' 'c']
 ['4' '5' '6']]


In [29]:
print(arr3[1,[1]])# second element of second element

['b']


In [30]:
ar = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(ar[0:2, 2]) 
# from both elements of the array return the element at index 2
#1-d array will be returned

[3 8]


In [31]:
print(arr3[0:,1:3]) # from all the rows
# slice the elements fron index 1 to 3(excluded)
# 2-d array will be returned

[['2' '3']
 ['b' 'c']
 ['5' '6']]


# Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

## dtype : returns the data type of the array

In [32]:
print(arr.dtype)

int32


In [33]:
arr6 = np.array(['Prateek', 'Alpha', 'Beta', 'Gamma', 'Falana', 'Dhimaka'])
print(arr6)
print(arr6.dtype)

['Prateek' 'Alpha' 'Beta' 'Gamma' 'Falana' 'Dhimaka']
<U7


In [34]:
# array with defined data types
arr7 = np.array([1,222,3,4,5,6],dtype = 'S')
print(arr7)
print(arr7.dtype)

[b'1' b'222' b'3' b'4' b'5' b'6']
|S3


In [35]:
arr7 = np.array([1,2,3,4],dtype = 'i4')
print(arr7)
print(arr7.dtype)

[1 2 3 4]
int32


### ValueError: 
In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.

## Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [36]:
newarr = arr7.astype('S') #int to string
print(newarr.dtype)

|S11


In [37]:
arr8 = np.array([1.45,0.32,4.76,8.34])
print(arr8.dtype)

float64


In [38]:
newarr1 = arr8.astype(int) # float to int
print(newarr1)
print(newarr1.dtype)

[1 0 4 8]
int32


In [39]:
newarr2 = newarr1.astype(bool) #int to bool
print(newarr2)
print(newarr2.dtype)

[ True False  True  True]
bool


In [40]:
newarr3 = arr8.astype(bool) # float to bool
print(newarr3)
print(newarr3.dtype)
# its not working properly

[ True  True  True  True]
bool


In [41]:
arr9 = np.array([1, 2, 3, 4, 5])
print("Original array: ",arr9)
x = arr9.copy()
y = arr9.view()
arr9[0] = 42
print("updated array: ",arr9)

print("Viewing updated array: ",y)


y[4] = 45 #making changes in view
print("newly updated view array: ",y)
print("New original array after making an update in view : ",arr9)

print("copied original array: ",x)


Original array:  [1 2 3 4 5]
updated array:  [42  2  3  4  5]
Viewing updated array:  [42  2  3  4  5]
newly updated view array:  [42  2  3  4 45]
New original array after making an update in view :  [42  2  3  4 45]
copied original array:  [1 2 3 4 5]


### Check if Array Owns it's Data

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [42]:
arr10 = np.array([1, 2, 3, 4, 5])

x1 = arr10.copy()
y2 = arr10.view()

print(x1.base)
print(y2.base)

None
[1 2 3 4 5]


In [43]:
print(arr4)

[[['1' '2' '3']
  ['4' '5' '6']]

 [['a' 'b' 'c']
  ['d' 'e' 'f']]

 [['7' '8' '9']
  ['10' '11' '12']]]


In [44]:
print(arr4.shape)

(3, 2, 3)


arr4 has 3 dimensions.
each dimension of arr4 has 2 dimensions.
In these inner 3 dimension, each dimension has 3 elements in it.

Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

In [45]:
arr11 = np.array([1, 2, 3, 4], ndmin=5)

print(arr11)
print('shape of array :', arr11.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# Array Reshaping 
By reshaping we can add or remove dimensions or change number of elements in each dimension.


Reshaped array when passed in 'base' returns the original array.
Which dipicts that the new array is the viw of the original array

### Question : 
Convert the following 1-D array with 24 elements into a 2-D array and a 3d array.

#### 2-d array : 
The outermost dimension will have 6 arrays, each with 4 elements.

#### 3-d array: 
the outermost dimension will have 3 dimensions the inner dimension will have 2 dimensions each with 4 elements.

In [46]:
arr12 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])
print("1-d array : \n",arr12)
print("Shape : ",arr12.shape)
d2 = arr12.reshape(6,4)
d3 = arr12.reshape(3,2,4)
print("\n2-d array : \n",d2)
print("Shape : ",d2.shape)
print("\n3-d array : \n",d3)
print("Shape : ",d3.shape)

1-d array : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape :  (24,)

2-d array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Shape :  (6, 4)

3-d array : 
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
Shape :  (3, 2, 4)


## Unknown Dimension

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass 
# -1 
as the value, and NumPy will calculate this number for you.
#### Note: We can not pass -1 to more than one dimension.

In [47]:
arr13 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr4 = arr13.reshape(2, 2, -1)

print(newarr4)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [48]:
# flatten = Converting n dimension array to 1-d array
arr14 = arr13.reshape(-1)
print(arr14)

[1 2 3 4 5 6 7 8]


# Iterating Arrays

In [49]:
for i in arr14:
    print(i)

1
2
3
4
5
6
7
8


In [50]:
# printing all the scalars in 2-d array
for i in ar:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10


In [51]:
# printing all the scalars in 3-d array
for i in d3:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [52]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


# Joining numpy arrays

In [53]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr = np.concatenate((arr1, arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [54]:
# for 2d arrays

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2), axis  = 1)# along rows
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


## Joining Arrays Using Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [55]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr) #stacking

[[1 4]
 [2 5]
 [3 6]]


In [59]:
arr3 = np.array([1, 2, 3])

arr4 = np.array([4, 5, 6])

arr2 = np.hstack((arr3, arr4))

print(arr2) #stacking along rows

[1 2 3 4 5 6]


In [60]:
arr3 = np.array([1, 2, 3])

arr4 = np.array([4, 5, 6])

arr2 = np.vstack((arr3, arr4))

print(arr2) #stacking along columns

[[1 2 3]
 [4 5 6]]


In [61]:
arr3 = np.array([1, 2, 3])

arr4 = np.array([4, 5, 6])

arr2 = np.dstack((arr3, arr4))

print(arr2) #stacking along rows

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
map()