<a href="https://colab.research.google.com/github/er-prateek-tripathi/Numpy/blob/main/Fundamentals/ArrayCreation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
# Empty Array
var1 = np.empty([2,4], dtype = int)

In [7]:
print("Type: ", type(var1))
print("Shape: ", var1.shape)

Type:  <class 'numpy.ndarray'>
Shape:  (2, 4)


In [8]:
# Empty Like

var2 = np.empty_like(var1, dtype = float)
print('Type: ', type(var2))
print('Shape: ', var2.shape)

Type:  <class 'numpy.ndarray'>
Shape:  (2, 4)


In [12]:
# 2D array with ones
# k = +ve, kth index in row
# k = -ve, kth index in col

var3 = np.eye(4, 5, k = -2, dtype=int)
print(var3)
print('Type: ', type(var3))
print('Shape: ', var3.shape)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]]
Type:  <class 'numpy.ndarray'>
Shape:  (4, 5)


In [13]:
# Identity Array

var4 = np.identity(3, dtype = int)
print(var4)
print('Type: ', type(var4))
print('Shape: ', var4.shape)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
Type:  <class 'numpy.ndarray'>
Shape:  (3, 3)


In [16]:
# Ones Array

var5 = np.ones((5, 4), dtype = int)

print(var5)
print('Type: ', type(var5))
print('Shape: ', var5.shape)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Type:  <class 'numpy.ndarray'>
Shape:  (5, 4)


In [18]:
a = np.arange(8)
a = a.reshape((2, 4))

var6 = np.ones_like(a, dtype = int)

print(var6)
print('Type: ', type(var6))
print('Shape: ', var6.shape)

[[1 1 1 1]
 [1 1 1 1]]
Type:  <class 'numpy.ndarray'>
Shape:  (2, 4)


In [19]:
# Zeros Array

var7 = np.zeros((3, 3), dtype=int)

print(var7)
print('Type: ', type(var7))
print('Shape: ', var7.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Type:  <class 'numpy.ndarray'>
Shape:  (3, 3)


In [20]:
b = np.arange(6)
b = b.reshape((2, 3))

var8 = np.zeros_like(b, dtype = int)

print(var8)
print('Type: ', type(var8))
print('Shape: ', var8.shape)

[[0 0 0]
 [0 0 0]]
Type:  <class 'numpy.ndarray'>
Shape:  (2, 3)


In [21]:
# array

var9 = np.array([2, 3, 4])
var9

array([2, 3, 4])

In [22]:
type(var9)

numpy.ndarray

In [23]:
var9 = np.array([2, 3, 4.5])
var9

array([2. , 3. , 4.5])

In [25]:
np.array([[1, 2], [3, 4]]) # 2 dimension Array

array([[1, 2],
       [3, 4]])

In [27]:
np.array([1, 2, 3], ndmin = 2) # 1D to 2D

array([[1, 2, 3]])

In [28]:
np.array([4, 5, 6], dtype = complex) # array with complex numbers

array([4.+0.j, 5.+0.j, 6.+0.j])